#!/usr/bin/env python3

from setuptools import setup
import os

VERSION = "0.1"

with open(os.path.join("sshbl", "__init__.py"), 'w') as f:
    f.write("""# Generated by setup.py
__version__ = '%s'""" % VERSION)

setup(name='sshbl',
     version=VERSION,
     author='James Lu',
     author_email='james@overdrivenetworks.com',
     description='SSH Banner Blacklisting Suite',
     license="GPL",
     url="https://github.com/jlu5/sshbl",
     packages=['sshbl'],
     entry_points={'console_scripts': [
        'bannergrabber = sshbl.bannergrabber:main',
        'sshbl = sshbl.sshbl:main',
         ]}
)
